Repository AY2021S2-CS2103T-W13-1/tp, pull requests merged in 2021-03, with the labels that each got.

#49 Update 'User Guide' : Update Add and Close Command
  docs/UserGuide.md
Labels: type.Documentation

#50 Update 'Developer Guide' : Update Close Use Case
  docs/DeveloperGuide.md
Labels: type.Documentation

#51 Modify Window Size : Update Default Window Size
  src/main/java/seedu/dictionote/commons/core/GuiSettings.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#79 Add 'Notes' Feature : Mark a note as done
  src/main/java/seedu/dictionote/logic/commands/EditNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/MarkAsDoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/logic/parser/MarkAsDoneNoteCommandParser.java
  src/main/java/seedu/dictionote/model/note/Note.java
  src/test/java/seedu/dictionote/logic/commands/MarkAsDoneNoteCommandTest.java
Labels: priority.Low, type.Story

#82 Add 'Notes' Feature: add listnote command
  src/main/java/seedu/dictionote/logic/commands/ListNoteCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/model/Model.java
  src/test/java/seedu/dictionote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/dictionote/logic/commands/ListNoteCommandTest.java
Labels: priority.High, type.Story

#97 Update 'Documentation' : Updating 'User Guide'
  docs/UserGuide.md
Labels: type.Documentation

#115 Add 'Notes' feature: Mark as undone
  src/main/java/seedu/dictionote/logic/commands/MarkAsUndoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/logic/parser/MarkAsDoneNoteCommandParser.java
  src/main/java/seedu/dictionote/logic/parser/MarkAsUndoneNoteCommandParser.java
  src/main/java/seedu/dictionote/model/note/Note.java
  src/test/java/seedu/dictionote/logic/commands/MarkAsUndoneNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/parser/MarkAsDoneNoteCommandParserTest.java
  src/test/java/seedu/dictionote/logic/parser/MarkAsUndoneNoteCommandParserTest.java
Labels: priority.Medium, type.Story

#119 Add 'Note' Feature : Edit Mode
  README.md
  docs/UserGuide.md
  src/main/java/seedu/dictionote/commons/core/Messages.java
  src/main/java/seedu/dictionote/logic/LogicManager.java
  src/main/java/seedu/dictionote/logic/commands/AddNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/EditModeCommand.java
  src/main/java/seedu/dictionote/logic/commands/EditModeQuitCommand.java
  src/main/java/seedu/dictionote/logic/commands/EditModeSaveCommand.java
  src/main/java/seedu/dictionote/logic/commands/EditNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/ExitCommand.java
  src/main/java/seedu/dictionote/logic/commands/MarkAsDoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/ShowNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/enums/UiAction.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/model/Model.java
  src/main/java/seedu/dictionote/model/ModelManager.java
  src/main/java/seedu/dictionote/ui/MainWindow.java
  src/main/java/seedu/dictionote/ui/NoteContentConfig.java
  src/main/java/seedu/dictionote/ui/NoteContentPanel.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DictionaryContentCard.fxml
  src/main/resources/view/DictionaryListContentCard.fxml
  src/main/resources/view/DictionaryListDefinitionCard.fxml
  src/main/resources/view/NoteContentPanel.fxml
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/dictionote/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/EditModeCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/EditModeQuitCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/EditModeSaveCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/ExitCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/MarkAsDoneNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/parser/DictionoteParserTest.java
  src/test/java/seedu/dictionote/testutil/TypicalNoteContentConfig.java
Labels: type.Story

#122 Add 'Notes' feature : Mark All As Undone Note Command
  src/main/java/seedu/dictionote/logic/commands/MarkAllAsUndoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/MarkAsUndoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/test/java/seedu/dictionote/logic/commands/MarkAllAsUndoneNoteCommandTest.java
Labels: priority.Medium, type.Story

#130 Update 'Documentation' : Update UG and DG for mark as undone note and mark all as undone note
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#134 Update 'Documentation' : Update UserGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
Labels: type.Documentation

#133 Update 'Documentation' : Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.png
Labels: type.Documentation

#142 Update Documentation : Update Logic Class Diagram (DG)
  docs/diagrams/LogicClassDiagram.puml
  docs/images/LogicClassDiagram.png
Labels: type.Documentation

#153 Add 'UI' Feature : Set UI divider Position Command
  src/main/java/seedu/dictionote/logic/commands/SetContactDividerPositionCommand.java
  src/main/java/seedu/dictionote/logic/commands/SetDictionaryDividerPositionCommand.java
  src/main/java/seedu/dictionote/logic/commands/SetDividerPositionCommand.java
  src/main/java/seedu/dictionote/logic/commands/SetMainDividerPositionCommand.java
  src/main/java/seedu/dictionote/logic/commands/SetNoteDividerPositionCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/logic/parser/ParserUtil.java
  src/test/java/seedu/dictionote/logic/commands/SetContactDividerPositionCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/SetDictionaryDividerPositionCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/SetMainDividerPositionCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/SetNoteDividerPositionCommandTest.java
  src/test/java/seedu/dictionote/logic/parser/DictionoteParserTest.java
  src/test/java/seedu/dictionote/logic/parser/DictionoteParserTest.java~
  src/test/java/seedu/dictionote/logic/parser/ParserUtilTest.java
  src/test/java/seedu/dictionote/testutil/TypicalUiActions.java
Labels: type.Story

#155 Add 'Notes' feature : Merge two notes
  src/main/java/seedu/dictionote/logic/LogicManager.java
  src/main/java/seedu/dictionote/logic/commands/MergeNoteCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/logic/parser/MergeNoteCommandParser.java
  src/main/java/seedu/dictionote/model/Model.java
  src/main/java/seedu/dictionote/model/ModelManager.java
  src/test/java/seedu/dictionote/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/dictionote/logic/commands/MergeNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/parser/MergeNoteCommandParserTest.java
Labels: priority.Medium, type.Story

#154 Add 'Note' Feature: Sort Note by Time
  src/main/java/seedu/dictionote/logic/LogicManager.java
  src/main/java/seedu/dictionote/logic/commands/ListCommandCommand.java
  src/main/java/seedu/dictionote/logic/commands/SortNoteByTimeCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/model/Model.java
  src/main/java/seedu/dictionote/model/ModelManager.java
  src/main/java/seedu/dictionote/model/NoteBook.java
  src/main/java/seedu/dictionote/model/note/UniqueNoteList.java
  src/test/java/seedu/dictionote/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/SortNoteByTimeCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/SortNoteCommandTest.java
Labels: priority.Medium, type.Story

#158 Add 'Notes' Feature : Convert notes into txt
  src/main/java/seedu/dictionote/logic/commands/ConvertTxtNoteCommand.java
  src/main/java/seedu/dictionote/logic/parser/ConvertTxtNoteCommandParser.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/java/seedu/dictionote/model/note/Note.java
  src/test/java/seedu/dictionote/logic/parser/ConvertTxtNoteCommandParserTest.java
Labels: priority.Medium, type.Story

#162 Update UI Theme
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low

#160 Add 'Help' Feature : ListCommandDetails
  src/main/java/seedu/dictionote/logic/commands/ListCommandCommand.java
  src/main/java/seedu/dictionote/logic/commands/ListCommandContactCommand.java
  src/main/java/seedu/dictionote/logic/commands/ListCommandDictionaryCommand.java
  src/main/java/seedu/dictionote/logic/commands/ListCommandNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/ListCommandUiCommand.java
  src/main/java/seedu/dictionote/logic/parser/DictionoteParser.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/dictionote/logic/commands/ListCommandContactCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/ListCommandDictionaryCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/ListCommandNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/ListCommandUiCommandTest.java
  src/test/java/seedu/dictionote/logic/parser/DictionoteParserTest.java
Labels: type.Story

#172 Update 'UI' Feature : Correct UiAction Feedback on Multiple Command
  src/main/java/seedu/dictionote/logic/commands/FindContentCommand.java
  src/main/java/seedu/dictionote/logic/commands/FindDefinitionCommand.java
  src/main/java/seedu/dictionote/logic/commands/FindNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/ListContentCommand.java
  src/main/java/seedu/dictionote/logic/commands/ListNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/MarkAllAsUndoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/MarkAsDoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/MarkAsUndoneNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/SortNoteByTimeCommand.java
  src/main/java/seedu/dictionote/logic/commands/SortNoteCommand.java
  src/test/java/seedu/dictionote/logic/commands/ListNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/MarkAsUndoneNoteCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/SortNoteByTimeCommandTest.java
  src/test/java/seedu/dictionote/logic/commands/SortNoteCommandTest.java
Labels: type.Bug

#173 Update Documentation: Add Screenshots and Implementation
  docs/DeveloperGuide.md
  docs/images/ConvertNoteToTxtContent.png
  docs/images/ConvertNoteToTxtEnd.png
  docs/images/ConvertNoteToTxtResult.png
  docs/images/ConvertNoteToTxtStart.png
Labels: type.Documentation

#174 Update Documentation: Add Developer Guide for Merge Note
  docs/DeveloperGuide.md
  docs/images/MergeNoteAfter.png
  docs/images/MergeNoteBefore.png
Labels: type.Documentation
