Repository AY2021S2-CS2103T-W13-1/tp, pull requests merged in 2021-04, with the labels that each got.

#235 Update 'UserGuide' : Fix Minor Error
  docs/UserGuide.md
Labels: type.Bug

#240 Update ug addnotecommand
  docs/UserGuide.md
  src/main/java/seedu/dictionote/logic/commands/EditNoteCommand.java
  src/main/java/seedu/dictionote/logic/commands/MarkAsUndoneNoteCommand.java
Labels: priority.Medium, type.Bug, type.Documentation

#238 fix grammatical error
  src/main/java/seedu/dictionote/logic/commands/EditNoteCommand.java
Labels: severity.Verylow, type.Bug

#247 Update addnote User Guide
  docs/UserGuide.md
Labels: priority.Medium, type.Bug, type.Documentation

#253 Update 'Help' Feature : Change listcommand format and update UI
  src/main/java/seedu/dictionote/logic/commands/ListCommandCommand.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug

#263 Add `Documentation` : Update About Us Otto
  docs/AboutUs.md
Labels: type.Documentation

#270 Update 'UserGuide' : Update FAQ and more feature section, Fix images
  docs/UserGuide.md
  docs/images/UiOrientation.png
Labels: type.Documentation

#267 Update 'DeveloperGuide' : Fix error in diagram
  docs/diagrams/OpenCommandSequenceDiagram.puml
  docs/diagrams/ToggleCommandSequenceDiagram.puml
  docs/images/OpenCommandSequenceDiagram.png
  docs/images/ToggleCommandSequenceDiagram.png
Labels: type.Bug

#275 Update 'Note' Feature : Fix Bug where shown note not updated after editnote command
  src/main/java/seedu/dictionote/logic/commands/EditNoteCommand.java
Labels: priority.High, severity.High, type.Bug

#272 Update Documentation : Ppp finalize and Update Dictionote Description
  docs/index.md
  docs/team/godjuansan.md
  docs/team/jessen11.md
  docs/team/teohoekeat.md
Labels: type.Documentation

#268 Update Documentation: Add use cases for Notes
  docs/DeveloperGuide.md
Labels: type.Documentation

#282 Update Documentation : Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Documentation

#288 Update `Documentation` : Add missing features
  docs/UserGuide.md
Labels: type.Documentation

#287 Update Documentation : Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Documentation

#292 Update Documentation : Update User Guide
  docs/UserGuide.md
Labels: type.Documentation

#302 Update Documentation : Fix User Guide Screenshots
  docs/UserGuide.md
Labels: type.Bug, type.Documentation
